version: '3.8'

services:
  django_gateway:
    build: ./liff_backend
    env_file:
      - .env
    environment:
      - DEBUG=False
      - SECRET_KEY=supersecret123
      - GATEWAY_DB_NAME=API_Gateway
      - GATEWAY_DB_USER=postgres
      - GATEWAY_DB_PASSWORD=admin
      - GATEWAY_DB_HOST=gateway_postgres
      - GATEWAY_DB_PORT=5432
      - ODOO_URL=${ODOO_URL}
      - ODOO_DB=${ODOO_DB}
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis
      - gateway_postgres
    networks:
      - default
      - odoo_kovic_net

  gateway_postgres:
    image: postgres:15
    container_name: gateway_postgres
    restart: always
    environment:
      POSTGRES_DB: API_Gateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:6.2
    container_name: redis
    networks:
      - default

  nginx_gateway:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./liff_backend/static:/static
    depends_on:
      - django_gateway
    networks:
      - default
      - odoo_kovic_net

networks:
  default:
    name: liff_default
    external: false

  odoo_kovic_net:
    external: true
    name: odoo-kovic_default

volumes:
  pgdata:
