# Generated by Django 4.2.16 on 2025-03-24 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lineuser_created_at_lineuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
