# Generated by Django 4.2.16 on 2025-04-08 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_odoojwttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoojwttoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 5, 25, 24, 340705, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PermissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.odoojwttoken')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=256)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='api.odoojwttoken')),
            ],
        ),
        migrations.CreateModel(
            name='AllowedEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_endpoints', to='api.odoojwttoken')),
            ],
        ),
    ]
