# Generated by Django 4.2.16 on 2025-04-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_odoojwttoken_expires_at_permissionscope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoojwttoken',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
