# Generated by Django 4.2.16 on 2025-04-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_odoojwttoken_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedendpoint',
            name='path',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='allowedendpoint',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.odoojwttoken'),
        ),
    ]
