# Generated by Django 4.2.16 on 2025-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_allowedendpoint_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionscope',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
    ]
