# Generated by Django 4.2.16 on 2025-04-10 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_permissionscope_can_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionscope',
            name='can_approve',
        ),
        migrations.RemoveField(
            model_name='permissionscope',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='permissionscope',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='permissionscope',
            name='can_read',
        ),
        migrations.RemoveField(
            model_name='permissionscope',
            name='can_update',
        ),
        migrations.AddField(
            model_name='permissionscope',
            name='access_actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
    ]
