# Generated by Django 4.2.16 on 2025-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_permissionscope_can_approve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionscope',
            name='access_actions',
        ),
        migrations.AddField(
            model_name='permissionscope',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionscope',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionscope',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionscope',
            name='can_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionscope',
            name='can_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionscope',
            name='can_update',
            field=models.BooleanField(default=False),
        ),
    ]
