# Generated by Django 4.2.16 on 2025-04-11 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_permissionscope_access_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionscope',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permissionscope',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.odoojwttoken'),
        ),
        migrations.AlterUniqueTogether(
            name='permissionscope',
            unique_together={('token', 'model_name')},
        ),
    ]
