# Generated by Django 4.2.16 on 2025-04-23 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_permissionscope_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIGatewayToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='odoojwttoken',
            name='project_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apigatewaytoken'),
        ),
    ]
