# Generated by Django 4.2.16 on 2025-05-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_apigatewaytoken_odoojwttoken_project_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odoojwttoken',
            name='project_token',
        ),
        migrations.DeleteModel(
            name='APIGatewayToken',
        ),
    ]
